###############
#nanopore pipeline step 3 - trimming adapters with cutadapt
###############
universe         = vanilla
getenv           = true
accounting_group = $ENV(CONDOR_GROUP)
request_cpus            = 3
request_memory          = 3
notification            = Error
Requirements            =(TARGET.Machine=!="cylon.datasci.danforthcenter.org")

log              = $(basedir)/$(outdir)/$(region)/logFiles/$(sample).cutadapt_trimming.$(region).log
output           = $(basedir)/$(outdir)/$(region)/logFiles/$(sample).cutadapt_trimming.$(region).out
error            = $(basedir)/$(outdir)/$(region)/logFiles/$(sample).cutadapt_trimming.$(region).err

executable       = /usr/local/bin/cutadapt
arguments        = -g GGTATCAACGCAGAGTACATGGG -e 0.15 -n 2 -j 3  --info-file $(basedir)/$(outdir)/$(region)/logFiles/$(sample).info.$(region).out -o $(basedir)/$(outdir)/$(region)/$(sample).trimmed.$(region).fastq --untrimmed-output $(basedir)/$(outdir)/$(region)/$(sample).untrimmed.$(region).fastq $(basedir)/$(outdir)/$(indir)/$(sample).fastq

transfer_executable = False
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

######################Change variable below this line
basedir = /home/mkramer/projects/target_capture/ruby_round2/data/
outdir = 4_cutadapt_trim_5p_3p_adapters
indir = 3p
region = 5p
queue sample from $(basedir)/$(outdir)/$(indir)/samples.txt
